#!/bin/bash
PROJECT_ROOT="$(git rev-parse --show-toplevel)"
terraform output -raw firebase_android_config | base64 -d > "${PROJECT_ROOT}/app/google-services.json"

# This line tests the script with a base64 example
# echo "ewogICJwcm9qZWN0X2luZm8iOiB7CiAgICAicHJvamVjdF9udW1iZXIiOiAiMTIzNDU2Nzg5IiwKICAgICJwcm9qZWN0X2lkIjogInRlc3QtcHJvamVjdC1pZCIsCiAgICAic3RvcmFnZV9idWNrZXQiOiAidGVzdC1wcm9qZWN0LWlkLmFwcHNwb3QuY29tIgogIH0sCiAgImNsaWVudCI6IFsKICAgIHsKICAgICAgImNsaWVudF9pbmZvIjogewogICAgICAgICJtb2JpbGVzZGtfYXBwX2lkIjogIjE6MTIzNDU2Nzg5OmFuZHJvaWQ6YWJjZGVmMTIzNDU2IiwKICAgICAgICAiYW5kcm9pZF9jbGllbnRfaW5mbyI6IHsKICAgICAgICAgICJwYWNrYWdlX25hbWUiOiAiY29tLmV4YW1wbGUuc3VucmlzZWFwcG5ldyIKICAgICAgICB9CiAgICAgIH0sCiAgICAgICJhcGlfa2V5IjogWwogICAgICAgIHsKICAgICAgICAgICJjdXJyZW50X2tleSI6ICJmYWtlLWFwaS1rZXktZm9yLXRlc3Rpbmctb25seSIKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJzZXJ2aWNlcyI6IHsKICAgICAgICAiYXBwaW52aXRlX3NlcnZpY2UiOiB7CiAgICAgICAgICAib3RoZXJfcGxhdGZvcm1fb2F1dGhfY2xpZW50IjogW10KICAgICAgICB9CiAgICAgIH0KICAgIH0KICBdLAogICJjb25maWd1cmF0aW9uX3ZlcnNpb24iOiAiMSIKfQ=="| base64 -d > "${PROJECT_ROOT}/app/google-services.json"
